### ISSUE TITLE
Viết wiki: PTQTNV: Chỉnh sửa phần Chức năng quản lý đơn hàng

### ISSUE THREAD

**Issue by davidmorrison-08-30** [davidmorrison-08-30/E-COMMERCE-STORE#11]

**Comment by TuongTran1301** [comment]
Tuong fixed "Chức năng quản lý đơn hàng"

**Comment by davidmorrison-08-30** [comment]
- Phần "Xác nhận đơn hàng" và "Xử lý đơn hàng" nên gộp lại thành phần mới, đặt tên là "Kiểm tra đơn hàng"

- Giữ nguyên hai chấm đầu dòng đầu tiên ở mục "Xác nhận đơn hàng" 

- Chấm đầu dòng cuối cùng ở mục "Xử lý đơn hàng" nên sửa lại thành "Quyết định giao hàng hoặc từ chối và xóa đơn hàng
ra khỏi database"

- Những chấm đầu dòng khác thì thay thế bằng một chấm đầu dòng có nội dung là kiểm tra tính hợp lệ của đơn hàng theo các tiêu chí được đưa ra trong trang [Đơn hàng](https://github.com/davidmorrison-08-30/E-COMMERCE-STORE/wiki/%C4%90%C6%A0N-H%C3%80NG)

- Phần "Theo dõi và cập nhật đơn hàng" đổi tên thành "Cập nhật trạng thái đơn hàng". Trong phần này chỉ ghi là admin sửa trạng thái đơn hàng từ "Pending" sang Delivered sau khi giao hàng xong

- Cửa hàng chỉ có DUY NHẤT 1 nhân viên nên sẽ không có đội ngũ giao hàng nào

- Xem [sơ đồ Use case cho admin](https://github.com/davidmorrison-08-30/E-COMMERCE-STORE/wiki/S%C6%A0-%C4%90%E1%BB%92-USE-CASE#use-case-cho-admin) để nắm đc cái sườn
